export default {
  login: "adamwathan",
  id: 4323180,
  node_id: "MDQ6VXNlcjQzMjMxODA=",
  avatar_url: "https://avatars.githubusercontent.com/u/4323180?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/adamwathan",
  html_url: "https://github.com/adamwathan",
  followers_url: "https://api.github.com/users/adamwathan/followers",
  following_url:
    "https://api.github.com/users/adamwathan/following{/other_user}",
  gists_url: "https://api.github.com/users/adamwathan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/adamwathan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/adamwathan/subscriptions",
  organizations_url: "https://api.github.com/users/adamwathan/orgs",
  repos_url: "https://api.github.com/users/adamwathan/repos",
  events_url: "https://api.github.com/users/adamwathan/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/adamwathan/received_events",
  type: "User",
  site_admin: false,
  name: "Adam Wathan",
  company: null,
  blog: "",
  location: "Ontario, Canada",
  email: null,
  hireable: null,
  bio: "Creator of Tailwind CSS, author of Refactoring UI, host of Full Stack Radio.",
  twitter_username: null,
  public_repos: 157,
  public_gists: 28,
  followers: 7909,
  following: 12,
  created_at: "2013-05-02T15:35:48Z",
  updated_at: "2022-03-15T11:35:38Z",
};
